version: "3"

services:
  meilisearch:
    # image: getmeili/meilisearch:latest
    image: getmeili/meilisearch:v1.6.0-rc.7
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
