site_name: Meilisearch Python Async
site_description: A Python async client for the Meilisearch API
site_url: https://meilisearch-python-async.paulsanders.dev

theme:
  name: material
  locale: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
repo_name: sanders41/meilisearch-python-async
repo_url: https://github.com/sanders41/meilisearch-python-async

nav:
  - Home: index.md
  - API:
    - AsyncClient: async_client_api.md
    - Client: client_api.md
    - AsyncIndex: async_index_api.md
    - Index: index_api.md
  - Pydantic: pydantic.md

plugins:
  - mkdocstrings
